<?php

namespace App\Commands;

use App\Traits\OutputsFiles;
use Illuminate\Support\Facades\File;
use LaravelZero\Framework\Commands\Command;

class Clean extends Command
{
    use OutputsFiles;

    /**
     * The signature of the command.
     *
     * @var string
     */
    protected $signature = 'clean';

    /**
     * The description of the command.
     *
     * @var string
     */
    protected $description = 'Deletes all files generated by the scrape and build commands';

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        File::deleteDirectory(base_path("$this->outputDirectory"));
    }
}
